# Site settings
title: Yuri MX's Garden
description: "Yuri's Blog"
baseurl: ""
url: ""

# User settings
username: Yuri MX
user_title: Director & Developer for Balala Fairies Group
email: reimu-mx@outlook.com
twitter_username:
github_username: yurimx
gplus_username:
linkedin_public_url:
disqus_username:
profile_picture: https://github.com/yurimx/yurimx.github.io/raw/img/mx.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/yurimx
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: yurimacs
    url: https://gitee.com/yurimx/yurimacs
  - name: yuriconfig
    url: https://github.com/yurimx/yuriconfig

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
